# Generated by Django 5.2.6 on 2025-09-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(default='GH₵', max_length=3),
        ),
    ]
