# Generated by Django 5.2.6 on 2025-09-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_product_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_static',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
